### PR TITLE
Update qick to version 0.2.211

### PR DESCRIPTION
**Pull request by rodolfocarobene**
I'm updating qibosoq to support the latest version of qick in order to support the latest version of the firmware

Checklist before merge:
- [ ] Reviewers confirm new code works as expected.
- [ ] Tests are passing.
- [ ] Documentation is updated.

### CODE REVIEW

**Comment by rodolfocarobene** [comment]
Hi @JavierSerranoGarcia, have you tested this updated version? Does it work?

**Comment by JavierSerranoGarcia** [comment]
Hi @rodolfocarobene, I am trying but as usual, I am having problems. The first one is just creating the platform, something has changed

`  File "/nfs/users/javier.serrano/qiboDev/qibolab/src/qibolab/backends.py", line 25, in __init__
    self.platform = create_platform(platform, runcard)
  File "/nfs/users/javier.serrano/qiboDev/qibolab/src/qibolab/__init__.py", line 55, in create_platform
    return module.create()
  File "/home/users/javier.serrano/qiboDev/qibolab_platforms_qrc/spinq10q_610_zcu216.py", line 36, in create
    channels |= Channel("L3-21", port=controller[0])  # readout probe
TypeError: 'RFSoC' object is not subscriptable`

I have pulled the last version of the repositories but it still complains.

**Comment by stavros11** [comment]
@JavierSerranoGarcia, this is due to a change we did recently,
```py
controller[0]
```
needs to be changed to
```py
controller.ports(0)
```
It is already fixed in the main branch of qibolab_platforms_qrc.

**Comment by JavierSerranoGarcia** [comment]
Running the qibosoq server I am getting the following error. I do not know if there is a problem with qibosoc or in Qick (they have made changes in the  API)

(pynq-venv) xilinx@ZCU216Bpynq:~/qibosoq$ sudo -E python -m qibosoq
library loaded!
resetting clocks: 245.76 491.52
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/share/pynq-venv/lib/python3.8/site-packages/qibosoq/__main__.py", line 13, in <module>
    serve(cfg.HOST, cfg.PORT)
  File "/usr/local/share/pynq-venv/lib/python3.8/site-packages/qibosoq/server.py", line 163, in serve
    server.qick_soc = QickSoc(bitfile=cfg.QICKSOC_LOCATION)
  File "/usr/local/share/pynq-venv/lib/python3.8/site-packages/qick/qick.py", line 291, in __init__
    self.map_signal_paths()
  File "/usr/local/share/pynq-venv/lib/python3.8/site-packages/qick/qick.py", line 315, in map_signal_paths
    getattr(self, key).configure_connections(self)
  File "/usr/local/share/pynq-venv/lib/python3.8/site-packages/qick/drivers/generator.py", line 113, in configure_connections
    super().configure_connections(soc)
  File "/usr/local/share/pynq-venv/lib/python3.8/site-packages/qick/drivers/generator.py", line 222, in configure_connections
    raise RuntimeError("failed to trace tProc port for %s - ran into unrecognized IP block %s" % (self.fullpath, block))
RuntimeError: failed to trace tProc port for axis_sg_int4_v1_1 - ran into unrecognized IP block axis_tmux_v1_0

**Comment by rodolfocarobene** [comment]
In the error you sent I see 
```
 RuntimeError: failed to trace tProc port for axis_sg_int4_v1_1 - ran into unrecognized IP block axis_tmux_v1_0
```
I believe that QICK is trying to find an IP (using PYNQ), but that IP it's not present anymore in your firmware.

**Comment by JavierSerranoGarcia** [comment]
Hi @rodolfocarobene, the problem was I was not using the right version of Qick (0.2.211) because qibosoq installs quick with 181.

I have just installed teh right version but still I get the following error 

> (pynq-venv) xilinx@ZCU216Bpynq:~/jupyter_notebooks/qick$ sudo -E python -m qibosoq
> 
> library loaded!
> 
> Traceback (most recent call last):
> 
>   File "/usr/lib/python3.8/runpy.py", line 193, in _run_module_as_main
>     return _run_code(code, main_globals, None,
> 
>   File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
>     exec(code, run_globals)
> 
>   File "/usr/local/share/pynq-venv/lib/python3.8/site-packages/qibosoq/__main__.py", line 7, in <module>
>     from qibosoq.server import serve
> 
>   File "/usr/local/share/pynq-venv/lib/python3.8/site-packages/qibosoq/server.py", line 17, in <module>
>     from qibosoq.programs.pulse_sequence import ExecutePulseSequence
> 
>   File "/usr/local/share/pynq-venv/lib/python3.8/site-packages/qibosoq/programs/pulse_sequence.py", line 8, in <module>
>     from qibosoq.programs.flux import FluxProgram
> 
>   File "/usr/local/share/pynq-venv/lib/python3.8/site-packages/qibosoq/programs/flux.py", line 8, in <module>
>     from qick.qick_asm import QickRegister
> 
> ImportError: cannot import name 'QickRegister' from 'qick.qick_asm' (/usr/local/share/pynq-venv/lib/python3.8/site-packages/qick/qick_asm.py)

**Comment by JavierSerranoGarcia** [comment]
Hi again @rodolfocarobene , I am seen that now this QickRegister is in another class qick.asm_v1. What's the best way of fix it? I can modify it locally but it should be fixed in main, no?

**Comment by rodolfocarobene** [comment]
Actually this (and the qick version) is fixed in this PR, not in main. I'm waiting to be sure everything is working to merge it.
Therefore you should use this branch

**Comment by JavierSerranoGarcia** [comment]
Hi @rodolfocarobene  , now I have a firmware with a multiplexed generator at full speed working with Qick 0.2.230. I am using Pynq 2.7, the image created  by Sara Sussman for the ZCU216.  I do not want to spoil the configuration. 

How do you think you could install qibosoq ? 

- in the pynq-env? or in a new one?
- without dependencies?
- Should I use the branch qickupdate?
- any other suggestion?

Last question is why qibosoq has as dependencies Pynq 3.0?

**Comment by rodolfocarobene** [comment]
Hi @JavierSerranoGarcia, did this branch work for you in the last tests? Since at the moment I do not have cold qubits available, I am relying on you to test updates in order to merge pull requests.

Anyway, coming to your questions:
> in the pynq-env? or in a new one?

What do you mean with pynq_env? QICK works only if run by someone with sudo powers, so generally you have to install everything in the sudo environment.

> without dependencies?

If there were problems, maybe, but in general there should not be. In  particular, if you install qibosoq with dependencies, it will just try to fix the "wrong" dependencies. Pynq should be ok.

> Should I use the branch qickupdate?

At the moment, the main branch depends on qick<=0.2.181 and the qickupdate branch on qick==0.2.211 so neither branch would work. If you need it I can update the qickupdate branch up to qick==0.2.230

> Last question is why qibosoq has as dependencies Pynq 3.0?

Qibosoq does not directly depend on pynq, but just on qick. So it depends on pynq the same way qick depends on it.
QICK depends on pynq>2.5 so both pynq==2.7 and pynq==3.0 should work. Automatically, it will choose to install pynq==3.0 because it's the newer version, but if pynq is already installed it should skip that installation.

**Comment by JavierSerranoGarcia** [comment]
Hi @rodolfocarobene 

> Hi @JavierSerranoGarcia, did this branch work for you in the last tests? Since at the moment I do not have cold qubits available, I am relying on you to test updates in order to merge pull requests.
Sorry I was aware you were waiting for me. But let's fix it out
> 
> Anyway, coming to your questions:
> 
> > in the pynq-env? or in a new one?
> 
> What do you mean with pynq_env? QICK works only if run by someone with sudo powers, so generally you have to install everything in the sudo environment.

pynq-env is virtual environment that comes with the Pynq image. You find it at /usr/local/shared/pynq-env
The sudo environment is a virtual one or just what you do with sudo?
> 
> > without dependencies?
> 
> If there were problems, maybe, but in general there should not be. In particular, if you install qibosoq with dependencies, it will just try to fix the "wrong" dependencies. Pynq should be ok.
> 
> > Should I use the branch qickupdate?
> 
> At the moment, the main branch depends on qick<=0.2.181 and the qickupdate branch on qick==0.2.211 so neither branch would work. If you need it I can update the qickupdate branch up to qick==0.2.230

Please update to 0.2.230 and I will try to install it with dependencies

Thank you Rodolfo
Javi

> 
> > Last question is why qibosoq has as dependencies Pynq 3.0?
> 
> Qibosoq does not directly depend on pynq, but just on qick. So it depends on pynq the same way qick depends on it. QICK depends on pynq>2.5 so both pynq==2.7 and pynq==3.0 should work. Automatically, it will choose to install pynq==3.0 because it's the newer version, but if pynq is already installed it should skip that installation.

**Comment by rodolfocarobene** [comment]
Hi @JavierSerranoGarcia, I have updated this branch to qick 0.2.230 (it should now support all version from 0.2.211 to 0.2.230)

**Comment by JavierSerranoGarcia** [comment]
Hi @rodolfocarobene, finally the server is working and accepting requests with the following versions

_Firmware qick_qibo_v2, Qick 0.2.230, pynq 2.7, ZCU216b. Qibosoq 0.1.1 branch qickupdate_

I have tested it with the qibo client doing spectroscopy of two resonators

Tomorrow I will test it with qibocal.

**Comment by rodolfocarobene** [comment]
Awesome! Let me know if also qibocal works :-)

**Comment by JavierSerranoGarcia** [comment]
I have not fully checked all the routines but did spectroscopy with qibocal and it worked.  Next week I will check all the routines in a real chip.

**Review by alecandido — APPROVED** [review]
As you said, changes are quite minimal, and I actually already reviewed yesterday... but the review was pending 🤦

File: src/qibosoq/programs/base.py [hunk 1]
```diff
@@ -74,6 +73,9 @@ def __init__(
         # pylint: disable-next=too-many-function-args
         super().__init__(soc, asdict(qpcfg))
 
+        self.reps = qpcfg.reps  # must be done after QickProgram init
```
[the remark this answers is not in the document]
Comment (rodolfocarobene) [reply src/qibosoq/programs/base.py:76]: If I remember correctly, the problem was for `self.soft_avgs` because of this:
https://github.com/openquantumhardware/qick/blob/6c823b348e9c49a5db3b35b98c698cf874218c4f/qick_lib/qick/averager_program.py#L31-L34

[the remark this answers is not in the document]
Comment (alecandido) [reply src/qibosoq/programs/base.py:76]: Ok, I see. But this class is not inheriting (not even indirectly) from the `AveragerProgram`.

Maybe we should make a `qibosoq.AveragerProgram` (even with a different name), or directly define these attributes in `ExecutePulseSequence` and `ExecuteSweep`.
